### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by ryan-gerstenkorn-sp** [stevetarver/jenkins-pipe#1]
Hey, was looking over this project and have been really impressed with it. Wanted to ask if you would consider licensing it under a MIT, or similar license?

Unrelated but also have been messing around with getting this running with https://github.com/jenkinsci/jenkinsfile-runner using a docker in docker setup. Didn't require too many changes to this project but if you're interested in accepting some PR's on how to set that up let me know.

**Comment by stevetarver** [comment]
Hey Ryan, glad you found some interesting ideas here. Feel free to copy the source and do what ever you want with it - make it your own.

I will not be licensing or otherwise supporting this code sample - I no longer work in this space and simply do not have the time.

cheers
~ steve

**Comment by ryan-gerstenkorn-sp** [comment]
That's understandable. I mostly just wanted to check if you where ok with me reusing this code, so this actually resolves my concerns.

Thank you the quick response here as well as letting me reuse this project.
